#!/usr/bin/env ruby
# frozen_string_literal: true

$stdout.sync = true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require '../lib/newport'

Newport::Help.show && abort if ARGV.length.zero? || ARGV[0] == 'help'

case ARGV[0]
when 'new'
  Newport::New.process ARGV
when 'build'
  Newport::Build.process ARGV
else
  Newport.logger.abort_with "fatal: 'newport #{ARGV.first}' could not be found.".red
end
